### ISSUE TITLE
Resize and fit seems buggy in the examples

### ISSUE THREAD

**Issue by EddieOne** [samme/phaser-plugin-game-scale#2]
I expect the canvas to always be 100%, sometimes after vigorous resizing, the canvas gets stuck in a smaller size.

![image](https://user-images.githubusercontent.com/1835156/48661730-f5086580-ea33-11e8-8ee8-3007eb39599a.png)

Also, the fit part doesn't seem to scale game objects in resize-and-fit. It centers but no resize.

![image](https://user-images.githubusercontent.com/1835156/48661739-2123e680-ea34-11e8-89f3-82c74a1bd494.png)

**Comment by samme** [comment]
Can you be more specific?

All of the plugin's scaling (`fit`, `resize-and-fit`) is whole-canvas. It doesn't modify game objects at all.

If you don't get the results you expect from scaling, examine these values (shown in the examples):

- `this.gameScale.width`
- `this.gameScale.height`
- `this.sys.game.config.width`
- `this.sys.game.config.height`

Also, if you cycle through the modes in the [examples](https://github.com/samme/phaser-plugin-game-scale/tree/v1.3.1/examples), you won't get back to the game's original size, because the `resize` and `resize-and-fit` modes have already changed those values.

**Comment by EddieOne** [comment]
Right, with `fit` it will scale the canvas which effectively scales game objects.

When, i try 'resize-and-fit', the canvas scale stays at 1. Is it expected behavior?

**Comment by samme** [comment]
It would be if the min and max lengths aren't set, or if the available area is still within the min and max lengths. In that case no scaling is done, only resizing.

> When, i try 'resize-and-fit', the canvas scale stays at 1. Is it expected behavior?

**Comment by EddieOne** [comment]
Yeah, that seems to work well enough. The only downside is if someone wants 100% x 100%, no easy way to do that. This will work for me, it just needs to be in a frame with constant ratio when scaling. Otherwise, it seems the matchbox look is unavoidable. One improvement could be to center the canvas inside the match box.
